ASM = nasm
SRC_DIR = src
BUILD_DIR = build

.PHONY: all floppy_image kernel bootloader clean always

#
# Floppy Disk
#

floppy_image: $(BUILD_DIR)/main_floppy.img

# The default target that runs when you just type 'make'
all: $(BUILD_DIR)/main_floppy.img

$(BUILD_DIR)/main_floppy.img: bootloader kernel
	powershell -Command "Copy-Item '$(BUILD_DIR)/main.bin' -Destination '$(BUILD_DIR)/main_floppy.img'"
	powershell -Command "$$f = [System.IO.File]::OpenWrite('$(BUILD_DIR)/main_floppy.img'); $$f.SetLength(1440KB); $$f.Close()"

#
# BOOTLOADER
#
bootloader: $(BUILD_DIR)/bootloader.bin: always


#
# KERNAL
#
$(BUILD_DIR)/main.bin: $(SRC_DIR)/main.asm
	$(ASM) $(SRC_DIR)/main.asm -f bin -o $(BUILD_DIR)/main.bin
